#!/bin/bash

. "/vagrant/setup/helper-functions.sh"
. "/vagrant/setup/load-variables.sh"

function emptydb {
  mysqldump --add-drop-table "${DB[name]}" | grep "DROP TABLE" | mysql "${DB[name]}"
  cl ""${DB[name]}" is now empty"
}

# Are you sure?
read -r -p $'\e[36m'"This will delete every table in the "${DB[name]}" database. Are you sure you want to continue? [y/N] "$'\e[0m' response
case $response in
    [yY][eE][sS]|[yY])
        emptydb
        ;;
    *)
        exit
        ;;
esac
