#!/bin/bash

. "/vagrant/setup/helper-functions.sh"
. "/vagrant/setup/load-variables.sh"


# Make sure DB exists
if [ -d "/var/lib/mysql/${DB[name]}" ]; then
    cl "Error: This script expects a database called ${DB[name]} but that does not exist." -e
    exit
fi

# Find most recent dump
MOST_RECENT=`find "/vagrant/sql-local-dump/" -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d " "`

# Make sure there is a dump to import
if [ ${#MOST_RECENT} == 0 ]; then
  cl "No local dumps for this project have been created yet." -e
  exit
fi

FILE_NAME=${MOST_RECENT##*/}

importdb() {
	zcat $1 | mysql -u root --password=password ${DB[name]}
	cl "$2 imported sucsesfully" -s
}

if [[ $* == *-y* ]]; then # check for y flag
  importdb $MOST_RECENT $FILE_NAME
else

  # Are you sure?
  read -r -p $'\e[36m'"This will import $FILE_NAME over the top of your database. Are you sure? [y/N] "$'\e[0m' response
  case $response in
      [yY][eE][sS]|[yY])
          importdb $MOST_RECENT $FILE_NAME
          ;;
      *)
          exit
          ;;
  esac

fi
